site_name: Digital Design and Development Club (3DC)
site_url: https://3dc.opensutd.org/
docs_dir: docs/

# repo_name: '3DCdsc/3dcdsc.github.io'
# repo_url: 'https://github.com/3DCdsc/3dcdsc.github.io'

# Copyright
copyright: Digital Design and Development Club (3DC) &copy; 2019 - 2021. All rights reserved.

# Theme Configuration
theme:
  name: material
  language: en
  favicon: imgs/code.svg
  icon:
    logo: fontawesome/solid/code
  features:
    - navigation.tabs
  palette:
    scheme: slate
    primary: teal
    accent: indigo

# Extensions
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: "#"
  - pymdownx.arithmatex:
      generic: true
  - attr_list

# Extra Style
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/3DCdsc
    - icon: fontawesome/brands/twitch
      link: https://www.twitch.tv/3dcdsc
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCF56lQD1HWv-0uOQSXrTmLw
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/sutd3dc/
    - icon: fontawesome/brands/telegram
      link: https://t.me/joinchat/C_Nni1C77ZlOVTdjU4yf4Q

# Navigation Menu
nav:
  - Home: "index.md"
  #     - Projects:
  #         - Projects: 'project.md'
  - Workshops:
      - Upcoming Workshops: "Workshops/upcoming_workshops.md"
      - Past Workshops: "Workshops/past_workshops.md"
      - Workshop Organiser Guide: "Workshops/workshop_guide.md"
  - Events:
    - Past Events:
      - Recess Week Challenge 2020:
          - Challenge Introduction: "Recess_Week_Challenge_Stuff/recess_week_challenge.md"
          - Cloud-based Lab: "Recess_Week_Challenge_Stuff/cloud_based_lab.md"
          - HackerRank Guide: "Recess_Week_Challenge_Stuff/guide.md"
          - Teaser Hints: "Recess_Week_Challenge_Stuff/teaser_hints.md"
          - Teaser Solution: "Recess_Week_Challenge_Stuff/teaser_sols.md"
          - Q1 Hints: "Recess_Week_Challenge_Stuff/q1_hints.md"
          - Q1 Solution: "Recess_Week_Challenge_Stuff/q1_sol.md"
          - Q2 Solution: "Recess_Week_Challenge_Stuff/q2_sol.md"
          - Q3 Hints: "Recess_Week_Challenge_Stuff/q3_hints.md"
          - Q3 Solution: "Recess_Week_Challenge_Stuff/q3_sol.md"
          - Q4 Solution: "Recess_Week_Challenge_Stuff/q4_sol.md"
          - Q5 Hints: "Recess_Week_Challenge_Stuff/q5_hints.md"
  - Google Tech Challenge 2021:
    - Introduction: "gtc.md"
    - "Web: Cookerino Website":
      - "Day 1: Back-end (Django) Development": "gtc/web/day1.md"
      - "Day 2: Front-end (React) Development": "gtc/web/day2.md"
    - Android:
      - Introduction: "gtc/android/android.md"
      - Day 0 - Environment Setup: "gtc/android/day0a.md"
      - Day 0 - Java Tutorial: "gtc/android/day0b.md"
      - Day 1 - Introduction to Android Studio: "gtc/android/day1_androidstudio.md"
      - Day 1 - Introduction to GUI: "gtc/android/day1_gui.md"
      - Day 1 - Java in Android: "gtc/android/day1_java.md"
      - Day 2.0 - Firebase Introduction: "gtc/android/day2-firebase-intro.md"
      - Day 2.1 - Adding Firebase to Your Project: "gtc/android/day2-firebase-sdk.md"
  - Meet The Team:
      - Core Team: "core_team.md"
      - Join Us:
        - Join 3DC Membership: "3dc_membership.md"
        - Join 3DC Core Team: "join_3dc_core.md"
